# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZCMctSRu0GrQCk-hCTVz4mYJ5Jm2Spqy
"""

print("hello")